config/routes.rb
Rails.application.routes.draw do
  resources :memberships do
    post 'toggle_membership', on: :member
  end
  resources :beer_clubs
  resources :users do
    post 'toggle_status', on: :member
    get 'recommendation', on: :member
  end
  root 'breweries#index'
  resources :beers
  resources :styles do
    get 'about', on: :collection
  end
  resources :breweries do
    post 'toggle_activity', on: :member
    get 'active', on: :collection
    get 'retired', on: :collection
  end
  resources :ratings do
    post 'toggle_arrow', on: :collection
  end
  resources :messages, only: [:index, :new, :create, :destroy]
  resources :messages do
    get 'list', on: :collection
  end
  resources :ratings, only: [:index, :new, :create, :show]
  delete 'ratings', to: 'ratings#destroy'
  resources :places, only: [:index]
  resource :session, only: [:new, :create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get 'test_sentry', to: 'application#test_sentry'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get 'kaikki_bisset', to: 'beers#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  post 'places', to: 'places#search'
  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'
  get 'calculator', to: 'misc#calculator'
end

app/models/membership.rb
class Membership < ApplicationRecord
  validate :membership_must_not_exist

  belongs_to :beer_club
  belongs_to :user

  def to_s
    "#{user.username}: #{beer_club.name}"
  end

  scope :confirmed, -> { where confirmed: true }
  scope :pending, -> { where confirmed: [nil, false] }

  private

  def membership_must_not_exist
    return unless Membership.exists?(user_id: user_id, beer_club_id: beer_club_id)

    errors.add(:base, "You are already a member of this beer club.")
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: %i[show edit update destroy]

  # GET /memberships or /memberships.json
  def index
    @memberships = Membership.all
    @confirmed_memberships = Membership.includes(:beer_club, :user).confirmed
    @pending_memberships = Membership.includes(:beer_club, :user).pending
  end

  # GET /memberships/1 or /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @memberships = Membership.all
    @membership = Membership.new
    @beer_clubs = BeerClub.all
    @user = current_user
  end

  # GET /memberships/1/edit
  def edit
    @beer_clubs = BeerClub.all
    @user = current_user
  end

  # POST /memberships or /memberships.json
  def create
    @membership = Membership.new(membership_params)
    respond_to do |format|
      if @membership.save
        @member = User.find(@membership.user_id).username
        @beer_club = BeerClub.find(@membership.beer_club_id)
        format.html { redirect_to @beer_club, notice: "Your membership is waiting for confirmation." }
      else
        @membership = Membership.find_by(membership_params)
        @beer_club = BeerClub.find(@membership.beer_club_id)
        format.html { redirect_to @beer_club, notice: "You are already a member." }
      end
      format.json { render :show, status: :created, location: @membership }
    end
  end

  # PATCH/PUT /memberships/1 or /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: "Membership was successfully updated." }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  def toggle_membership
    membership = Membership.find(params[:id])
    @beer_club = membership.beer_club
    @member = membership.user.username
    membership.update_attribute :confirmed, true
    redirect_to beer_club_path(@beer_club), notice: "Membership of #{@member} was confirmed."
  end

  # DELETE /memberships/1 or /memberships/1.json
  def destroy
    @beer_club = BeerClub.find(@membership.beer_club.id)
    @membership.destroy!

    respond_to do |format|
      format.html do
        redirect_to user_path(current_user),
                    status: :see_other,
                    notice: "Membership in #{@beer_club.name} ended."
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_membership
    @membership = Membership.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def membership_params
    params.require(:membership).permit(:beer_club_id, :user_id)
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_with(model: membership) do |form| %>
  <% if membership.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
        <% membership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :beer_club_id, style: "display: block" %>
    <%= form.select :beer_club_id, options_from_collection_for_select(@beer_clubs, :id, :to_s) %>
  </div>

  <div>
    <%= form.hidden_field :user_id, value: @user.id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/memberships/_membership.html.erb
<div id="<%= dom_id membership %>">
  <p>
    <strong>Beer club:</strong>
    <%= membership.beer_club.name %>
  </p>

  <p>
    <strong>User:</strong>
    <%= membership.user.username %>
  </p>

</div>

app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= render "form", membership: @membership %>

<br>

<div>
  <%= link_to "Show this membership", @membership %> |
  <%= link_to "Back to memberships", memberships_path %>
</div>

app/views/memberships/index.html.erb
<h1>Memberships</h1>

<div id="memberships">
  <% @memberships.each do |membership| %>
    <p>
    <%= membership.to_s %>
    </p>
    <p>
      <%= link_to "Show this membership", membership %>
    </p>
  <% end %>
</div>

<%= link_to("New membership", new_membership_path, class:'btn btn-primary') %>

app/views/memberships/new.html.erb
<h2>New membership</h2>

<%= render "form", membership: @membership %>

<br>

<div>
  <%= link_to "Back to memberships", memberships_path %>
</div>

app/views/memberships/show.html.erb
<%= render @membership %>

<div>
  <%= edit_and_destroy_buttons(@membership)%>
  <%= link_to "Back to memberships", memberships_path %>
</div>