config/routes.rb
Rails.application.routes.draw do
  resources :memberships do
    post 'toggle_membership', on: :member
  end
  resources :beer_clubs
  resources :users do
    post 'toggle_status', on: :member
    get 'recommendation', on: :member
  end
  root 'breweries#index'
  resources :beers
  resources :styles do
    get 'about', on: :collection
  end
  resources :breweries do
    post 'toggle_activity', on: :member
    get 'active', on: :collection
    get 'retired', on: :collection
  end
  resources :ratings do
    post 'toggle_arrow', on: :collection
  end
  resources :messages, only: [:index, :new, :create, :destroy]
  resources :messages do
    get 'list', on: :collection
  end
  resources :ratings, only: [:index, :new, :create, :show]
  delete 'ratings', to: 'ratings#destroy'
  resources :places, only: [:index]
  resource :session, only: [:new, :create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get 'test_sentry', to: 'application#test_sentry'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get 'kaikki_bisset', to: 'beers#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  post 'places', to: 'places#search'
  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'
  get 'calculator', to: 'misc#calculator'
end

app/models/beer_club.rb
class BeerClub < ApplicationRecord
  has_many :memberships
  has_many :members, through: :memberships, source: :user

  def to_s
    "#{name}, #{city}"
  end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :set_beer_club, only: %i[show edit update destroy]
  before_action :set_admin, only: %i[show destroy]
  helper_method :confirmed_member, :pending_member

  # GET /beer_clubs or /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all
    order = params[:order] || 'name'

    @beer_clubs = case order
                  when "name" then @beer_clubs.sort_by(&:name)
                  when "founded" then @beer_clubs.sort_by(&:founded)
                  when "city" then @beer_clubs.sort_by(&:city)
                  end
  end

  # GET /beer_clubs/1 or /beer_clubs/1.json
  def show
    @confirmed_memberships = @beer_club.memberships&.confirmed
    @pending_memberships = @beer_club.memberships&.pending
    @membership = Membership.new
    @membership.beer_club = @beer_club
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs or /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        Membership.create(beer_club: @beer_club, user: current_user, confirmed: true)
        format.html { redirect_to @beer_club, notice: "Beer club was successfully created, you are the first member." }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1 or /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: "Beer club was successfully updated." }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1 or /beer_clubs/1.json
  def destroy
    return unless @admin

    @beer_club.destroy!

    respond_to do |format|
      format.html { redirect_to beer_clubs_path, status: :see_other, notice: "Beer club was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_beer_club
    @beer_club = BeerClub.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def beer_club_params
    params.require(:beer_club).permit(:name, :founded, :city)
  end

  def confirmed_member(beer_club)
    current_user.memberships.exists?(beer_club_id: beer_club.id, confirmed: true)
  end

  def pending_member(beer_club)
    current_user.memberships.exists?(beer_club_id: beer_club.id, confirmed: [nil, false])
  end

  # def check_membership(beer_club)
  #  current_user.memberships.exists?(beer_club_id: beer_club.id)
  # end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_beer_club.html.erb
<div id="<%= dom_id beer_club %>">
  <h2>
    <%= beer_club.name %>
  </h2>

  <p>
    <strong>Founded:</strong>
    <%= beer_club.founded %>
  </p>

  <p>
    <strong>City:</strong>
    <%= beer_club.city %>
  </p>

    <p>
    <% unless beer_club.members.empty? %>
      <div data-testid="confirmed-member">
        <% unless @confirmed_memberships.empty? %>
          <strong>Members:</strong>
          </p>
          <% beer_club.memberships.confirmed&.each do |m| %>
          <p>
            <%= link_to m.user.username, m.user %>
          </p>
          <% end %>
        <% end %>
      </div>
      <div data-testid="pending-member">
        <% unless @pending_memberships.empty? %>
          <strong>Membership applications:</strong>
            <% beer_club.memberships.pending&.each do |m| %>
          <p></p>
            <%= link_to m.user.username, m.user %>
            <%= link_to "Confirm", toggle_membership_membership_path(m.id),
                data: {turbo_method: "post"}, class: "btn btn-outline-primary btn-sm" if confirmed_member(@beer_club) %>
          <p></p>
          <% end %>
        <% end %>
      </div>
    <% else %>
      <p> This beer club has no members. </p>
    <% end %>

</div>

app/views/beer_clubs/_form.html.erb
<%= form_with(model: beer_club) do |form| %>
  <% if beer_club.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
        <% beer_club.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-2">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control", placeholder: "Maaningan maistelijat" %>
  </div>

  <div class="mb-2">
    <%= form.label :founded, class: "form-label" %>
    <%= form.number_field :founded, class: "form-control", placeholder: 1995 %>
  </div>

  <div class="mb-2">
    <%= form.label :city, class: "form-label" %>
    <%= form.text_field :city, class: "form-control", placeholder: "Maaninka"%>
  </div>

  <div>
    <%= form.submit class:'btn btn-primary btn-sm' %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing beer club</h1>

<%= render "form", beer_club: @beer_club %>

<br>

<div>
  <%= link_to "Show this beer club", @beer_club %> |
  <%= link_to "Back to beer clubs", beer_clubs_path %>
</div>

app/views/beer_clubs/index.html.erb
<h1>Beer clubs</h1>

<div id="beer_clubs">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th scope="col"><%= link_to "Name", beer_clubs_path(order: "name") %></th>
        <th scope="col"><%= link_to "Founded", beer_clubs_path(order: "founded") %></th>
        <th scope="col"><%= link_to "City", beer_clubs_path(order: "city") %></th>
      </tr>
    </thead>
    <tbody>
      <% @beer_clubs.each do |beer_club| %>
        <tr>
          <th scope="row"><%= link_to beer_club.name, beer_club %></th>
          <td><%= beer_club.founded %></td>
          <td><%= beer_club.city %></td>
        </tr>
      <% end %>
  </table>
</div>

<%= link_to("New beer club", new_beer_club_path, class:'btn btn-primary') if current_user %>

app/views/beer_clubs/new.html.erb
<h1>New beer club</h1>

<%= render "form", beer_club: @beer_club %>

<br>

<div>
  <%= link_to "Back to beer clubs", beer_clubs_path %>
</div>

app/views/beer_clubs/show.html.erb
<%= render @beer_club %>

<div>
  <% if current_user %>
    <% if confirmed_member(@beer_club) %>
      <% membership = current_user.memberships.find_by(beer_club_id: @beer_club.id)%>
      <%= form_with(model: @membership, url: membership_path(membership), method: :delete) do |form| %>
        <%= form.hidden_field :beer_club_id, value: @beer_club.id %>
        <%= form.hidden_field :user_id, value: current_user.id %>
        <%= form.submit("End the membership", class:'btn btn-danger btn-sm') %>
      <% end %>
    <% else %>
      <% unless pending_member(@beer_club)%>
        <h4>Join this beer club:</h4>
        <%= form_with(model: @membership) do |form| %>
          <%= form.hidden_field :beer_club_id, value: @beer_club.id %>
          <%= form.hidden_field :user_id, value: current_user.id %>
          <%= form.submit "Join the beer club" %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  <br>
  <%= edit_and_destroy_buttons_admin(@beer_club)%>
  <%= link_to "Back to beer clubs", beer_clubs_path, class:"btn btn-primary" %>
</div>