config/routes.rb
Rails.application.routes.draw do
  resources :memberships do
    post 'toggle_membership', on: :member
  end
  resources :beer_clubs
  resources :users do
    post 'toggle_status', on: :member
    get 'recommendation', on: :member
  end
  root 'breweries#index'
  resources :beers
  resources :styles do
    get 'about', on: :collection
  end
  resources :breweries do
    post 'toggle_activity', on: :member
    get 'active', on: :collection
    get 'retired', on: :collection
  end
  resources :ratings do
    post 'toggle_arrow', on: :collection
  end
  resources :messages, only: [:index, :new, :create, :destroy]
  resources :messages do
    get 'list', on: :collection
  end
  resources :ratings, only: [:index, :new, :create, :show]
  delete 'ratings', to: 'ratings#destroy'
  resources :places, only: [:index]
  resource :session, only: [:new, :create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get 'test_sentry', to: 'application#test_sentry'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get 'kaikki_bisset', to: 'beers#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  post 'places', to: 'places#search'
  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'
  get 'calculator', to: 'misc#calculator'
end

app/models/user.rb
class User < ApplicationRecord
  include RatingAverage

  has_secure_password

  validates :username, uniqueness: true,
                       length: { in: 3..30 }
  validates :password, length: { minimum: 4, message: "Password must have at least 4 chacters." },
                       format: { with: /([a-zA-Z]*[A-Z]+[a-zA-Z]*[0-9]+[a-zA-Z]*|[a-zA-Z]*[0-9]+[a-zA-Z]*[A-Z]+[a-zA-Z]*)/,
                                 message: "Password must have at least one capital letter and one number." }

  has_many :ratings, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships

  scope :admin, -> { where(admin: true) }
  scope :blocked, -> { where(blocked: true) }

  def rating_summary
    if ratings.count == 0
      "#{username} has no ratings."
    else
      "#{username} has made #{ratings.count} #{'rating'.pluralize(ratings.count)}, average rating #{average_rating}"
    end
  end

  # list of the names of the beerclubs the user has membembership in
  def club_names
    beer_clubs.map(& :to_s)
  end

  def favorite_beer
    return nil if ratings.empty?

    ratings.max_by(&:score).beer
  end

  def favorite_style
    favorite(:style)
  end

  def favorite_brewery
    favorite(:brewery)
  end

  def favorite(grouped_by)
    return nil if ratings.empty?

    grouped_ratings = ratings.group_by { |rating| rating.beer.send(grouped_by) }
    averages = grouped_ratings.transform_values do |ratings|
      total_score = ratings.sum(&:score)
      total_score.to_f / ratings.size
    end
    averages.max_by { |_r, avg_score| avg_score }&.first&.name
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :set_blocked_users, only: %i[show edit update]
  before_action :set_admin, only: %i[show edit update]

  # GET /users or /users.json
  def index
    @users = User.includes(:ratings).all
  end

  # GET /users/1 or /users/1.json
  def show
    return unless turbo_frame_request?

    @rating = @user.ratings.find(params[:rating_id])
    render partial: 'rating', locals: { rating: @rating }
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def toggle_status
    user = User.find(params[:id])
    user.update_attribute :blocked, !user.blocked

    new_status = user.blocked? ? "closed" : "open"
    redirect_to user, notice: "User account status changed to #{new_status}"
  end

  def recommendation
    # simulate a delay in calculating the recommendation
    sleep(2)
    ids = Beer.pluck(:id)
    # our recommendation us just a randomly picked beer...
    random_beer = Beer.find(ids.sample)
    render partial: 'recommendation', locals: { beer: random_beer }
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? && @user == current_user && @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    if @user == current_user
      @user.destroy!
      session.delete(:user_id)
    end

    respond_to do |format|
      format.html { redirect_to users_path, status: :see_other, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_edit_and_destroy_buttons(item, current_user)
    return unless item == current_user

    edit = link_to('Update', url_for([:edit, item]), class: "btn btn-primary")
    del = link_to('Destroy', item, class: "btn btn-danger", data: { 'turbo-method': :delete, turbo_confirm: "Are you sure?" })
    raw("#{edit} #{del}")
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div>
      <%= form.label :username, style: "display: block" %>
      <%= form.text_field :username %>
    </div>
  <% end %>

  <div>
    <%= form.label :password, style: "display: block"%>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block"%>
    <%= form.password_field :password_confirmation %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_rating.html.erb
<%= turbo_frame_tag "rating" do %>
  <h4><%= @rating.beer.name %></h4>
  <p><%= "Style #{@rating.beer.style}"%></p>
  <p><%= "Brewed by #{@rating.beer.brewery.name}"%></p>
  <p><%= "Rated #{@rating.rated}"%></p>
<% end %>

app/views/users/_ratings.html.erb
<div data-controller="ratings" class="ratings mb-4">
  <% @user.ratings.each do |rating| %>
    <div class="rating">
      <% if @user == current_user %>
        <input type="checkbox" name="ratings[]" value="<%= rating.id %>"/>
      <% end %>
      <span>
        <%= link_to rating.to_s, user_path(@user, rating_id: rating.id, turbo_frame: "rating"), data: { turbo_frame: "rating" } %>
      </span>
    </div>
  <% end %>
  <% if @user == current_user %>
    <span> Select all / deselect all
    <input type="checkbox" data-action="change->ratings#toggleSelection"/></span>
    <br>
    <button data-action="click->ratings#destroy">Delete selected</button>
  <% end %>
</div>

app/views/users/_recommendation.html.erb
<%= turbo_frame_tag "beer_recommendation_tag" do %>
  <div>
    <h4>Recommendation based on your ratings</h4>

    <p><%= link_to beer.name, beer %> by <%= link_to beer.brewery.name, beer.brewery %></p>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>
  <%= "Change password for user #{@user.username}" %>
</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <p>
      <%= link_to(user.username, user) %>
      <p>Has made <%= "#{user.ratings.size}"%> ratings, average rating <%= "#{user.average_rating}" %></p>
      <% if user.blocked? && current_user&.admin? %>
        <span class="badge bg-primary">Account closed</span>
      <% end %>
    </p>
  <% end %>
</div>

<%= link_to("Create new user", new_user_path, class:'btn btn-primary') %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<div id="<%= dom_id @user %>">
  <p>
    <h2>Userpage of
        <%= @user.username %>
    </h2>
  </p>
  <% if @user.blocked? && @current_user&.admin? %>
    <span class="badge bg-primary">Account closed</span>
  <% end %>
  <p>
    <%= @user.rating_summary %>
  </p>
  <p>
    <%= "Favorite beer style: #{@user.favorite_style}" unless @user.ratings.empty? %>
  </p>
  <p>
    <%= "Favorite brewery: #{@user.favorite_brewery}" unless @user.ratings.empty? %>
  </p>

  <% unless @user.ratings.empty? %>
    <h3>Ratings</h3>
    <%= render partial: 'ratings' %>
  <% end %>

  <%= turbo_frame_tag "rating" do %>
  <% end %>

  <%= turbo_frame_tag "beer_recommendation_tag", src: recommendation_user_path do %>
    Calculating the recommendation...
  <% end %>

  <% unless @user.beer_clubs.empty? %>
    <h3>Beer clubs</h3>
    <% unless @user.memberships.confirmed.empty?%>
      <h4>Member of</h4>
      <div data-testid="confirmed-member">
        <ul>
          <% @user.memberships.confirmed.each do |m| %>
            <li>
              <%= link_to m.beer_club.name, m.beer_club %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <% unless @user.memberships.pending.empty?%>
      <h4>Applied member of</h4>
      <div data-testid="pending-member">
        <ul>
          <% @user.memberships.pending.each do |m| %>
            <li>
              <%= link_to m.beer_club.name, m.beer_club %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% else %>
    <p>User has no memberships in beer clubs. </p>
  <% end %>
</div>

<div>
  <%= user_edit_and_destroy_buttons(@user, @current_user) %>
  <% if @user.blocked? %>
    <% button_text = "Open account" %>
  <% else %>
    <% button_text = "Close account" %>
  <% end %>
  <%= link_to button_text, toggle_status_user_path(@user.id),
    data: {turbo_method: "post"}, class: "btn btn-danger" if current_user&.admin? %>
  <p></p>
  <%= link_to "Back to users", users_path %>
</div>