config/routes.rb
Rails.application.routes.draw do
  resources :memberships do
    post 'toggle_membership', on: :member
  end
  resources :beer_clubs
  resources :users do
    post 'toggle_status', on: :member
    get 'recommendation', on: :member
  end
  root 'breweries#index'
  resources :beers
  resources :styles do
    get 'about', on: :collection
  end
  resources :breweries do
    post 'toggle_activity', on: :member
    get 'active', on: :collection
    get 'retired', on: :collection
  end
  resources :ratings do
    post 'toggle_arrow', on: :collection
  end
  resources :messages, only: [:index, :new, :create, :destroy]
  resources :messages do
    get 'list', on: :collection
  end
  resources :ratings, only: [:index, :new, :create, :show]
  delete 'ratings', to: 'ratings#destroy'
  resources :places, only: [:index]
  resource :session, only: [:new, :create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get 'test_sentry', to: 'application#test_sentry'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get 'kaikki_bisset', to: 'beers#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  post 'places', to: 'places#search'
  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'
  get 'calculator', to: 'misc#calculator'
end

app/models/brewery.rb
class Brewery < ApplicationRecord
  include RatingAverage
  extend TopRated

  validate :year_cannot_be_in_the_future_or_nil
  validates :name, presence: true
  validates :year, numericality: { greater_than: 1039,
                                   only_integer: true }

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  scope :active, -> { where active: true }
  scope :retired, -> { where active: [nil, false] }

  after_destroy_commit do
    next if Rails.env.test?

    broadcast_remove_to "breweries_index", target: self
    status = active? ? "active" : "retired"
    target_id = active? ? "active_brewery_count" : "retired_brewery_count"
    broadcast_replace_to "breweries_index", partial: "breweries/brewery_count", target: target_id,
                                            locals: { status: status }
  end

  after_create_commit do
    next if Rails.env.test?

    target_id1 = active? ? "active_brewery_rows" : "retired_brewery_rows"
    broadcast_append_to "breweries_index", partial: "breweries/brewery_row", target: target_id1

    status = active? ? "active" : "retired"
    target_id2 = active? ? "active_brewery_count" : "retired_brewery_count"
    broadcast_replace_to "breweries_index", partial: "breweries/brewery_count", target: target_id2,
                                            locals: { status: status }
  end

  def year_cannot_be_in_the_future_or_nil
    if year.nil?
      errors.add(:year, "can't be blank")
    elsif year > Time.now.year
      errors.add(:year, "can't be in the future.")
    end
  end

  def print_report
    puts name
    puts "Established at year #{year}"
    puts "Number of beers #{beers.count}"
  end

  def rating_summary
    "Brewery has #{ratings.count} #{'rating'.pluralize(ratings.count)}
    with an average of #{average_rating}"
  end

  def restart
    self.year = 2022
    puts "Changed year to #{year}"
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :ensure_that_signed_in, except: [:index, :show, :list, :active, :retired]
  before_action :set_brewery, only: %i[show edit update destroy]
  before_action :set_admin, only: %i[index show destroy active retired]

  # GET /breweries or /breweries.json
  def index
    @breweries = Brewery.order(:name)
    @active_breweries = Brewery.includes(:beers, :ratings).active
    @retired_breweries = Brewery.includes(:beers, :ratings).retired
  end

  def list
  end

  def active
    active_breweries = Brewery.includes(:beers, :ratings).active
    render partial: 'brewery_list',
           locals: { breweries: active_breweries, status: "active" }
  end

  def retired
    retired_breweries = Brewery.includes(:beers, :ratings).retired
    render partial: 'brewery_list',
           locals: { breweries: retired_breweries, status: "retired" }
  end

  # GET /breweries/1 or /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, !brewery.active

    new_status = brewery.active? ? "active" : "retired"
    old_status = brewery.active? ? "retired" : "active"

    render turbo_stream: [turbo_stream.replace("#{new_status}_brewery_count", partial: "brewery_count", locals: { status: new_status }),
                          turbo_stream.replace("#{old_status}_brewery_count", partial: "brewery_count", locals: { status: old_status }),
                          turbo_stream.remove(brewery),
                          turbo_stream.append("#{new_status}_brewery_rows", partial: "brewery_row", locals: { brewery: brewery })]
  end

  # POST /breweries or /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.turbo_stream {
          status = @brewery.active? ? "active" : "retired"
          render turbo_stream: [turbo_stream.append("#{status}_brewery_rows", partial: "brewery_row", locals: { brewery: @brewery }),
                                turbo_stream.replace("#{status}_brewery_count", partial: "brewery_count", locals: { status: status })]
        }
        format.html { redirect_to @brewery, notice: "Brewery was successfully created." }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1 or /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: "Brewery was successfully updated." }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1 or /breweries/1.json
  def destroy
    return unless @admin

    @brewery.destroy!

    respond_to do |format|
      format.turbo_stream {
        status = @brewery.active? ? "active" : "retired"
        render turbo_stream: [turbo_stream.remove(@brewery),
                              turbo_stream.replace("#{status}_brewery_count", partial: "brewery_count", locals: { status: status })]
      }
      format.html { redirect_to breweries_path, status: :see_other, notice: "Brewery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def brewery_params
    params.require(:brewery).permit(:name, :year, :active)
  end

  def set_admin
    @admin = current_user&.admin?
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_brewery.html.erb
<div id="<%= dom_id brewery %>">
  <h2>
    <%= brewery.name %>
      <% unless brewery.active %>
        <span class="badge bg-secondary">Retired</span>
      <% end %>
  </h2>

  <p>
    <em> Established in
    <%= brewery.year %></em>
  </p>

  <p> Beers count: 
  <%= brewery.beers.count %>
  </p>

  <% unless @brewery.beers.count == 0%>
    <h3>Beers</h3>
    <div>
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Style</th>
            <th scope="col">Rating</th>
          </tr>
        </thead>
        <tbody>
          <% @brewery.beers.each do |beer| %>
          <tr>
            <th scope="row"><%= link_to beer.name, beer %></th>
            <td><%= beer.style.name %></td>
            <td><%= round(beer.average_rating) %></td>
          </tr> 
          <% end %>
      </table>
    </div>
  <% end %>

  <p>
    <% if brewery.ratings.empty? %>
      Brewery has no ratings.
    <% else %>
      <%= brewery.rating_summary %>
    <% end %>
  </p>

</div>

app/views/breweries/_brewery_count.html.erb
<p id="<%= status %>_brewery_count">
  <%= "Number of #{status} breweries: #{Brewery.send(status).count}" %>
</p>

app/views/breweries/_brewery_list.html.erb
<%= turbo_frame_tag status do %>
  <div>
    <%= render "breweries/brewery_count", status: status %>
    <table class="table table-striped table-hover">
			<thead>
			<tr>
				<th scope="col">Name</th>
				<th scope="col">Established</th>
				<th scope="col">Beers</th>
				<th scope="col">Rating</th>
        <% if current_user %>
          <th scope="col">Change activity</th>
        <% end %>
        <% if current_user&.admin? %>
				  <th scope="col">Action</th>
        <% end %>
			</tr>
			</thead>
			<tbody id="<%= status %>_brewery_rows">
				<% breweries.each do |brewery| %>
					<%= render "breweries/brewery_row", brewery: brewery %>
				<% end %>
			</tbody>
    </table>
  </div>
<% end %>

app/views/breweries/_brewery_row.html.erb
<tr id="<%= dom_id(brewery) %>">
  <th scope="row"><%= link_to brewery.name, brewery, data: { turbo_frame: "_top"} %></th>
  <td><%= brewery.year %></td>
  <td><%= brewery.beers.count %></td>
  <td><%= round(brewery.average_rating) %></td>
  <% label = brewery.active? ? "Retire" : "Activate" %>
  <td><%= link_to label, toggle_activity_brewery_path(brewery.id),
    data: {turbo_method: "post"}, class: "btn btn-primary" if current_user %></td>
  <td><%= destroy_button_admin(brewery) if current_user&.admin? %></td>
</tr>

app/views/breweries/_form.html.erb
<%= form_with(model: brewery, data: {controller: "form", action: "turbo:submit-end->form#clear"}) do |form| %>
  <% if brewery.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
        <% brewery.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-2">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control", placeholder: "Imatran Kuohu", data: { form_target: "name" } %>
  </div>

  <div class="mb-2">
    <%= form.label :year, class: "form-label" %>
    <%= form.number_field :year, class: "form-control", placeholder: 1920, data: { form_target: "year" } %>
  </div>

  <div class="form-check">
  <%= form.label :active, class: "form-check-label" %> 
  <%= form.check_box :active, class: "form-check-input", type: "checkbox", data: { form_target: "active", checkbox_target: "input"} %>
  </div>
  <br>
  <div>
    <%= form.submit class:'btn btn-primary btn-sm' %>
  </div>
  <br>
  <button type="button" class="btn btn-primary btn-sm" data-action="form#clear">Clear form</button>
  </div>
  <br>
<% end %>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Show this brewery", @brewery %> |
  <%= link_to "Back to breweries", breweries_path %>
</div>

app/views/breweries/index.html.erb
<%= turbo_stream_from "breweries_index" %>

<h1>Breweries</h1>

<h2>Active</h2>

<%= turbo_frame_tag "active", src: active_breweries_path do %>
  Fetching brewery data...
<% end %>

<h2>Retired</h2>

<%= turbo_frame_tag "retired", src: retired_breweries_path do %>
  Fetching brewery data...
<% end %>

<p><%= turbo_frame_tag "new_brewery", src: new_brewery_path if current_user %></p>

app/views/breweries/list.html.erb
<h2>Breweries</h2>

<div id="breweries">
  <table id="brewerytable" class="table table-hover">
    <thead>
      <tr>
        <th> <span id="name">Name</span> </th>
        <th> <span id="year">Year</span> </th>
        <th> <span id="beers_count">Beercount</span> </th>
        <th> <span id="activity">Active</span> </th>
      </tr>
    </thead>
    <tbody id="brewerylist">
      <!-- rows should appear here, but they appear after <tbody> -->
    </tbody>
  </table>
</div>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= turbo_frame_tag "new_brewery" do %>
  <%= render "form", brewery: @brewery %>
<% end %>

<br>

<div>
  <%= link_to "Back to breweries", breweries_path %>
</div>

app/views/breweries/panimot.html.erb
 panimoita <%= @breweries.count %>
 

app/views/breweries/show.html.erb
<%= render @brewery %>

<div>
  <%= edit_and_destroy_buttons_admin(@brewery)%>
  <%= link_to "Back to breweries", breweries_path, class:"btn btn-primary" %>
</div>